#!/bin/sh

# The famous "get a menu of emojis to copy" script (by Luke Smith).

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/Scripts/emoji | dmenu -i -b -l 20 -fn 'Iosevka:style=Regular:pixelsize=16' -nb '#0F0F0F' -nf '#5083A9' -sb '#3B6585' -sf '#0F0F0F' -p '>' | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
