#!/bin/sh
#
# ufetch-arch - tiny system info for arch
#

## INFO

# user is already defined
HOST="$(hostname)"
OS="Arch Linux"
KERNEL="$(uname -sr)"
UPTIME="$(uptime -p | sed s:"up "::)"
PACKAGES="$(pacman -Q | wc -l)"
# shell is already defined
if [ -z "$WM" ]; then
	WM="$(grep -v "^#" "${HOME}/.xinitrc" | tail -n 1 | cut -d " " -f2)"
fi

## DEFINE COLORS

# probably don't change these
bc="$(tput bold)"	# bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"	# reset

# you can change these
lc="${bc}${c1}"		# labels
nc="${bc}${c1}"		# user and hostname
tc="${bc}${c7}"		# text
fc="${bc}${c1}"		# first color
sc="${c1}"		# second color

## OUTPUT

cat <<EOF
${bc}${c4}${USER}${rc}@${rc}${bc}${c4}${HOST}${rc}
${lc}${rc}-----------
${lc}OS:${rc}       ${OS}${rc}
${rc}${lc}KERNEL:${rc}   ${KERNEL}${rc}
${rc}${sc}${rc}${lc}UPTIME:${rc}   ${UPTIME}${rc}
${rc}${lc}PACKAGES:${rc} ${PACKAGES}${rc}
${rc}${lc}SHELL:${rc}    ${SHELL}${rc}
${rc}${lc}WM:${rc}       ${WM}${rc}
EOF
